# This file configures our Git hooks.
#
# For documentation, see: https://pre-commit.com/#plugins
# For editor autocomplete/hover documentation, use:
# https://github.com/redhat-developer/yaml-language-server
---
exclude: "^golden/.*/(golden[^/]*|input)"
repos:
- repo: local
  hooks:
  - id: fourmolu
    name: Format hs code with Fourmolu
    entry: ./scripts/run-format-wrapper.sh
    args:
    - inplace
    language: system
    types:
    - haskell
    require_serial: true
  # # Hlint takes a while to run and can be annoying, so it's disabled here.
  # - id: hlint
    # name: Lint hs code with Hlint
    # entry: hlint
    # args:
    # - -j
    # language: system
    # types:
    # - haskell
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-case-conflict
    name: Filenames differ only in case
  - id: check-executables-have-shebangs
    name: Check executables have shebangs
  - id: check-shebang-scripts-are-executable
    name: Check shebang scripts are executable
  - id: check-merge-conflict
    name: Forbid merge conflict markers
  - id: no-commit-to-branch
    name: Forbid commits to master
    args:
      - --branch
      - master
  - id: trailing-whitespace
    name: Trailing whitespace
    exclude_types:
      - diff  # .patch files
  - id: check-symlinks
    name: Check symlink destinations exist
  - id: destroyed-symlinks
    name: Check symlinks aren't changed to regular files
  - id: end-of-file-fixer
    name: Check files end with one newline
    exclude_types:
      - diff  # .patch files
  - id: fix-byte-order-marker
    name: Remove UTF-8 BOM
  - id: mixed-line-ending
    name: Forbid mixed line-endings
    args:
      - --fix=lf