 name: PR Branch Labeler

on: [pull_request]

jobs:
  label_prs:
    runs-on: [self-hosted, linux]
    steps:
    - name: Label PRs by Branch Name
      if: github.event.action == 'opened'
      uses: ffittschen/pr-branch-labeler@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}